;;; ligo-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "jsligo-mode" "jsligo-mode.el" (0 0 0 0))
;;; Generated autoloads from jsligo-mode.el

(register-definition-prefixes "jsligo-mode" '("jsligo-" "ligo-javascript-mode"))

;;;***

;;;### (autoloads nil "ligo-caml-mode" "ligo-caml-mode.el" (0 0 0
;;;;;;  0))
;;; Generated autoloads from ligo-caml-mode.el

(register-definition-prefixes "ligo-caml-mode" '("ligo-caml-mode" "mligo-"))

;;;***

;;;### (autoloads nil "ligo-mode" "ligo-mode.el" (0 0 0 0))
;;; Generated autoloads from ligo-mode.el

(autoload 'ligo-setup-lsp "ligo-mode" "\
Set up an LSP backend for ligo that will use `ligo-bin'." t)

(register-definition-prefixes "ligo-mode" '("ligo-"))

;;;***

;;; End of scraped data

(provide 'ligo-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ligo-mode-autoloads.el ends here
